<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>author</key>
	<string>Daan Leijen</string>
	<key>fileTypes</key>
	<array>
		<string>mdk</string>
		<string>md</string>
		<string>madoko</string>
		<string>markdown</string>
	</array>
	<key>firstLineMatch</key>
	<string>(Title:|Author:).*</string>
	<key>foldingStartMarker</key>
	<string>^~+\w+</string>
	<key>foldingStopMarker</key>
	<string>^~+\s*$</string>
	<key>name</key>
	<string>Madoko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#metadata</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>source.embedded</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(    |\t)(.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#+[^{]+</string>
			<key>name</key>
			<string>markup.heading.madoko</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\[(\^[^\]]+)\]\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.madoko</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(    |\t))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.madoko</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\[([^\]]+)\]\s*:(.*$)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ *(?:\| *|\+)[\-=~:]+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.heading.madoko</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?! *(\| *|\+))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[-=~:]*(\| *|\+)[-=~:]*</string>
					<key>name</key>
					<string>markup.heading.madoko</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>begin</key>
			<string>\{(?=(?:[^\\}]|\\.)+\}\s*$)</string>
			<key>end</key>
			<string>\}\s*$</string>
			<key>name</key>
			<string>meta.tag.preprocessor.xml</string>
			<key>patterns</key>
			<array>
			</array>
		</dict>
		<key>embedded</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^ *([*+\-]|\d+\.)\s</string>
					<key>name</key>
					<string>markup.heading.madoko</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(~+\s*Equation)\b(.*)(\n|$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.madoko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.embedded.latex</string>
					<key>end</key>
					<string>^~+</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.tex.latex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^~+[^{]+</string>
					<key>name</key>
					<string>entity.name.tag.madoko</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(`{3,}\s*javascript)\b\s*(.*)(\n|$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.embedded.javascript</string>
					<key>end</key>
					<string>^\s*(`{3,})\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(`{3,}\s*koka)\b\s*(.*)(\n|$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.embedded.koka</string>
					<key>end</key>
					<string>^\s*(`{3,})\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.koka</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((`{3,})\s*(\w+)?)(\s*.*)(\n|$)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.xml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.embedded</string>
					<key>end</key>
					<string>^\s*(`{3,})\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.any.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.madoko</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\[(\^?[\w\-\.:]+)\](?!\s*[\[(])</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#[\w\-\.:]+</string>
					<key>name</key>
					<string>constant.madoko</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.madoko</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.madoko</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\]\(\s*&lt;?([^\s&gt;)]*)&gt;?(?:\s+['"](.*?)['"])?\s*\)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*((?:[^\\*]|\\.)+)\*|\b_((?:[^\\_]|\\.)+)_\b</string>
					<key>name</key>
					<string>markup.italic.madoko</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.embedded</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(`+)((?:[^`]|(?!\1)`)*)\1</string>
				</dict>
				<dict>
					<key>match</key>
					<string>~([^\s\\]|\\.)+~|\^([^\s\\]|\\.)+\^</string>
					<key>name</key>
					<string>string.escape.madoko</string>
				</dict>
				<dict>
					<key>match</key>
					<string>~([^\s\\]|\\.)+~|\^([^\s\\]|\\.)+\^</string>
					<key>name</key>
					<string>string.escape.madoko</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[\`*{}\[\]()#+-\.!_&gt;~|\$'"?/ 
]</string>
					<key>name</key>
					<string>string.escape.madoko</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$(?=.*\$)</string>
					<key>contentName</key>
					<string>source.embedded.latex</string>
					<key>end</key>
					<string>\$|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.tex.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>metadata</key>
		<dict>
			<key>begin</key>
			<string>^(Title|Author)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.madoko</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=(\w|[\.~#])(?![\w\-\.#~,\s]*:))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.preprocessor.madoko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.metadata.madoko</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^([\.~#][\w\-\.#~,\s]*):</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.preprocessor.madoko</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!\s)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.*</string>
							<key>name</key>
							<string>meta.tag.preprocessor.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^\w[\w\-\.#~,\s]*:</string>
					<key>name</key>
					<string>meta.tag.preprocessor.madoko</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.madoko</string>
	<key>uuid</key>
	<string>c987c5f1-a938-47e3-a371-13d6c7542ed3</string>
</dict>
</plist>
